// SPDX-License-Identifier: GPL-2.0-or-later
#include QMK_KEYBOARD_H
#include "keymap_german.h"


// ─── Layers ─────────────────────────────────────────────────────────────────
enum corne_layers {
    _QWERTY,
    _KOY,
    _LOWER,
    _RAISE,
    _ADJUST,
};

enum custom_keycodes {
    KOY = QK_USER,
    QWERTY,
};


// ─── Shortcuts ──────────────────────────────────────────────────────────────
// Layer access
#define LOWER       MO(_LOWER)
#define RAISE       MO(_RAISE)
#define ADJUST      MO(_ADJUST)

// Thumb cluster: layer-tap and mod-tap
#define LOWERTAB    LT(_LOWER,  KC_TAB)   // tap=Tab,   hold=Lower
#define RAISEBSPC   LT(_RAISE,  KC_BSPC)  // tap=BSpc,  hold=Raise
#define ALTTPEN     LT(_ADJUST, KC_ENT)   // tap=Enter, hold=Adjust
#define ALTTPES     LALT_T(KC_ESC)        // tap=Esc,   hold=Alt
#define SHIFTSPACE  LSFT_T(KC_SPC)        // tap=Space, hold=Shift

// Home-row mods on the KOY layer (GASC: GUI, Alt, Shift, Ctrl)
#define HMOD_GUI    LGUI_T(DE_H)
#define HMOD_ALT    LALT_T(DE_A)
#define HMOD_SHIFT  LSFT_T(DE_E)
#define HMOD_CTRL   LCTL_T(DE_I)

// Ctrl+letter shortcuts (German layout)
#define N_PASTE     LCTL(KC_V)
#define N_COPY      LCTL(KC_C)
#define N_CUT       LCTL(KC_X)
#define N_UNDO      LCTL(DE_Z)
#define N_REDO      LCTL(DE_Y)

// AltGr fractions
#define ONEHALF     ALGR(DE_4)
#define ONETHIR     ALGR(DE_5)
#define ONEQUAR     ALGR(DE_6)


// ─── Keymap ─────────────────────────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │  ⭾   │  Q   │  W   │  E   │  R   │  T   │                │  Y   │  U   │  I   │  O   │  P   │  ⌫   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⌘   │  A   │  S   │  D   │  F   │  G   │                │  H   │  J   │  K   │  L   │  ;   │  '   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⇧   │  Z   │  X   │  C   │  V   │  B   │                │  N   │  M   │  ,   │  .   │  /   │  ⇧   │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │  ^   │ ⭾Lwr │ ⏎Adj │  │  ␣   │ ⌫Rse │  ⎋⎇  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_QWERTY] = LAYOUT_split_3x6_3(
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                                  KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
        KC_LGUI, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                                  KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,                                  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
                                            KC_LCTL, LOWERTAB, ALTTPEN,    KC_SPC,    RAISEBSPC, ALTTPES
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │  Z   │  K   │  .   │  O   │  ,   │  Y   │                │  V   │  G   │  C   │  L   │  ß   │  ⌫   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⌘   │  H⌘  │  A⎇  │  E⇧  │  I^  │  U   │                │  D   │  T   │  R   │  N   │  S   │  F   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⇧   │  X   │  Q   │  ä   │  ü   │  ö   │                │  B   │  P   │  W   │  M   │  J   │  ⇧   │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │  ^   │ ⭾Lwr │ ⏎Adj │  │  ␣⇧  │ ⌫Rse │  ⎋⎇  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_KOY] = LAYOUT_split_3x6_3(
        DE_Z,    DE_K,      DE_DOT,    DE_O,       DE_COMM,   DE_Y,                              DE_V,    DE_G,    DE_C,    DE_L,    DE_SS,   KC_BSPC,
        KC_LGUI, HMOD_GUI,  HMOD_ALT,  HMOD_SHIFT, HMOD_CTRL, DE_U,                              DE_D,    DE_T,    DE_R,    DE_N,    DE_S,    DE_F,
        KC_LSFT, DE_X,      DE_Q,      DE_ADIA,    DE_UDIA,   DE_ODIA,                           DE_B,    DE_P,    DE_W,    DE_M,    DE_J,    KC_RSFT,
                                                   KC_LCTL,   LOWERTAB,  ALTTPEN,    SHIFTSPACE, RAISEBSPC, ALTTPES
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  1   │  2   │  3   │  4   │  5   │                │  6   │  7   │  8   │  9   │  0   │  ⌦   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ Vol+ │  ▶⏸  │  ⇤   │  ⇥   │  ^Z  │                │  Z   │  ◁   │  ▽   │  △   │  ▷   │  ⎋   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ Vol- │  ⏮   │  ⏭   │  ^C  │  ^V  │                │  ²   │  ⌘   │  ⇧   │  ⎙   │  ¼   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │ Adj  │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_LOWER] = LAYOUT_split_3x6_3(
        _______, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                                  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        _______, KC_VOLU, KC_MPLY, KC_HOME, KC_END,  N_UNDO,                                DE_Z,    KC_LEFT, KC_DOWN, KC_UP,   KC_RIGHT,KC_ESC,
        _______, KC_VOLD, KC_MPRV, KC_MNXT, N_COPY,  N_PASTE,                               DE_SUP2, KC_LGUI, KC_LSFT, KC_PSCR, ONEQUAR, _______,
                                            _______, _______, _______,    _______, ADJUST,  _______
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  €   │  _   │  [   │  ]   │  ^   │                │  !   │  <   │  >   │  =   │  &   │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  \   │  /   │  {   │  }   │  *   │                │  ?   │  (   │  )   │  -   │  :   │  @   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  #   │  $   │  |   │  ~   │  ´   │                │  +   │  %   │  "   │  '   │  ;   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │  ⎇   │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_RAISE] = LAYOUT_split_3x6_3(
        _______, DE_EURO, DE_UNDS, DE_LBRC, DE_RBRC, DE_CIRC,                               DE_EXLM, DE_LABK, DE_RABK, DE_EQL,  DE_AMPR, _______,
        _______, DE_BSLS, DE_SLSH, DE_LCBR, DE_RCBR, DE_ASTR,                               DE_QUES, DE_LPRN, DE_RPRN, DE_MINS, DE_COLN, DE_AT,
        _______, DE_HASH, DE_DLR,  DE_PIPE, DE_TILD, DE_ACUT,                               DE_PLUS, DE_PERC, DE_DQUO, DE_QUOT, DE_SCLN, _______,
                                            _______, KC_LALT, _______,    _______, _______, _______
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ F12  │  F1  │  F2  │  F3  │  F4  │  F5  │                │  F6  │  F1  │  F2  │  F3  │  F4  │ F11  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  ⌘   │  ⎇   │  ⇧   │  ^   │CW_TOG│                │      │  F5  │  F6  │  F7  │  F8  │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │ KOY  │ QWE  │                │      │  F9  │ F10  │ F11  │ F12  │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_ADJUST] = LAYOUT_split_3x6_3(
        KC_F12,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                                 KC_F6,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F11,
        _______, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, CW_TOGG,                                XXXXXXX, KC_F5,   KC_F6,   KC_F7,   KC_F8,   XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, KOY,     QWERTY,                                XXXXXXX, KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______,
                                            _______, _______, _______,    _______, _______, _______
    ),

};


// ─── Chordal Hold ───────────────────────────────────────────────────────────
// Hand assignment for hold-tap arbitration:
//   'L' / 'R' — hold only fires if the next key is on the opposite hand.
//   '*'       — no chordal constraint (normal hold-tap behavior).
// Thumbs use '*' so layer-tap thumbs can still activate keys on the same hand
// (e.g. hold LOWERTAB on the left thumb to reach numbers on the left side).
const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM =
    LAYOUT_split_3x6_3(
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
                            '*', '*', '*',   '*', '*', '*'
    );


// ─── Caps Word ──────────────────────────────────────────────────────────────
// While Caps Word is active, these keys auto-shift; the rest end the word.
bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Letters: shift while Caps Word is on.
        case KC_A ... KC_Z:
        case DE_ADIA:
        case DE_ODIA:
        case DE_UDIA:
        case DE_SS:
            add_weak_mods(MOD_BIT(KC_LSFT));
            return true;
        // Continue without shift.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
        case DE_UNDS:
        case DE_MINS:
            return true;
        default:
            return false;  // any other key terminates Caps Word
    }
}


// ─── Default-layer toggles ──────────────────────────────────────────────────
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case KOY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_KOY);
            }
            return false;
        case QWERTY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWERTY);
            }
            return false;
    }
    return true;
}


// ─── OLED ───────────────────────────────────────────────────────────────────
#ifdef OLED_ENABLE
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (!is_keyboard_master()) {
        return OLED_ROTATION_180;
    }
    return rotation;
}

static void oled_render_layer_state(void) {
    oled_write_P(PSTR("Layer: "), false);
    switch (get_highest_layer(layer_state)) {
        case 0:
            if (biton32(default_layer_state) == _QWERTY) {
                oled_write_ln_P(PSTR("QWERTY"), false);
            } else if (biton32(default_layer_state) == _KOY) {
                oled_write_ln_P(PSTR("KOY"), false);
            }
            break;
        case _LOWER:  oled_write_ln_P(PSTR("Lower"),  false); break;
        case _RAISE:  oled_write_ln_P(PSTR("Raise"),  false); break;
        case _ADJUST: oled_write_ln_P(PSTR("Adjust"), false); break;
    }
}

static void oled_render_logo(void) {
    static const char PROGMEM crkbd_logo[] = {
        0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94,
        0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4,
        0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4,
        0
    };
    oled_write_P(crkbd_logo, false);
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        oled_render_layer_state();
    } else {
        oled_render_logo();
    }
    return false;
}
#endif // OLED_ENABLE
