// SPDX-License-Identifier: GPL-2.0-or-later
#include QMK_KEYBOARD_H
#include "keymap_german.h"


// ─── Layers ─────────────────────────────────────────────────────────────────
enum corne_layers {
    _QWERTY,
    _KOY,
    _LOWER,
    _RAISE,
    _ADJUST,
};

enum custom_keycodes {
    KOY = QK_USER,
    QWERTY,
};


// ─── Shortcuts ──────────────────────────────────────────────────────────────
// Layer access
#define LOWER       MO(_LOWER)
#define RAISE       MO(_RAISE)
#define ADJUST      MO(_ADJUST)

// Thumb cluster: layer-tap and mod-tap
#define LOWERTAB    LT(_LOWER,  KC_TAB)   // tap=Tab,   hold=Lower
#define RAISEBSPC   LT(_RAISE,  KC_BSPC)  // tap=BSpc,  hold=Raise
#define ALTTPEN     LT(_ADJUST, KC_ENT)   // tap=Enter, hold=Adjust
#define ALTTPES     LALT_T(KC_ESC)        // tap=Esc,   hold=Alt
#define SHIFTSPACE  LSFT_T(KC_SPC)        // tap=Space, hold=Shift

// Home-row mods on the KOY layer (GASC: GUI, Alt, Shift, Ctrl)
#define HMOD_GUI    LGUI_T(DE_H)
#define HMOD_ALT    LALT_T(DE_A)
#define HMOD_SHIFT  LSFT_T(DE_E)
#define HMOD_CTRL   LCTL_T(DE_I)

// Ctrl+letter shortcuts (German layout)
#define N_PASTE     LCTL(KC_V)
#define N_COPY      LCTL(KC_C)
#define N_CUT       LCTL(KC_X)
#define N_UNDO      LCTL(DE_Z)
#define N_REDO      LCTL(DE_Y)

// AltGr fractions
#define ONEHALF     ALGR(DE_4)
#define ONETHIR     ALGR(DE_5)
#define ONEQUAR     ALGR(DE_6)


// ─── Keymap ─────────────────────────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │  ⭾   │  Q   │  W   │  E   │  R   │  T   │                │  Y   │  U   │  I   │  O   │  P   │  ⌫   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⌘   │  A   │  S   │  D   │  F   │  G   │                │  H   │  J   │  K   │  L   │  ;   │  '   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⇧   │  Z   │  X   │  C   │  V   │  B   │                │  N   │  M   │  ,   │  .   │  /   │  ⇧   │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │  ^   │ ⭾Lwr │ ⏎Adj │  │  ␣   │ ⌫Rse │  ⎋⎇  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_QWERTY] = LAYOUT_split_3x6_3(
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                                  KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
        KC_LGUI, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                                  KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,                                  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
                                            KC_LCTL, LOWERTAB, ALTTPEN,    KC_SPC,    RAISEBSPC, ALTTPES
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │  Z   │  K   │  .   │  O   │  ,   │  Y   │                │  V   │  G   │  C   │  L   │  ß   │  ⌫   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⌘   │  H⌘  │  A⎇  │  E⇧  │  I^  │  U   │                │  D   │  T   │  R   │  N   │  S   │  F   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⇧   │  X   │  Q   │  ä   │  ü   │  ö   │                │  B   │  P   │  W   │  M   │  J   │  ⇧   │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │  ^   │ ⭾Lwr │ ⏎Adj │  │  ␣⇧  │ ⌫Rse │  ⎋⎇  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_KOY] = LAYOUT_split_3x6_3(
        DE_Z,    DE_K,      DE_DOT,    DE_O,       DE_COMM,   DE_Y,                              DE_V,    DE_G,    DE_C,    DE_L,    DE_SS,   KC_BSPC,
        KC_LGUI, HMOD_GUI,  HMOD_ALT,  HMOD_SHIFT, HMOD_CTRL, DE_U,                              DE_D,    DE_T,    DE_R,    DE_N,    DE_S,    DE_F,
        KC_LSFT, DE_X,      DE_Q,      DE_ADIA,    DE_UDIA,   DE_ODIA,                           DE_B,    DE_P,    DE_W,    DE_M,    DE_J,    KC_RSFT,
                                                   KC_LCTL,   LOWERTAB,  ALTTPEN,    SHIFTSPACE, RAISEBSPC, ALTTPES
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  1   │  2   │  3   │  4   │  5   │                │  6   │  7   │  8   │  9   │  0   │  ⌦   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ Vol+ │  ▶⏸  │  ⇤   │  ⇥   │  ^Z  │                │  Z   │  ◁   │  ▽   │  △   │  ▷   │  ⎋   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ Vol- │  ⏮   │  ⏭   │  ^C  │  ^V  │                │  ²   │  ⌘   │  ⇧   │  ⎙   │  ¼   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │ Adj  │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_LOWER] = LAYOUT_split_3x6_3(
        _______, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                                  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        _______, KC_VOLU, KC_MPLY, KC_HOME, KC_END,  N_UNDO,                                DE_Z,    KC_LEFT, KC_DOWN, KC_UP,   KC_RIGHT,KC_ESC,
        _______, KC_VOLD, KC_MPRV, KC_MNXT, N_COPY,  N_PASTE,                               DE_SUP2, KC_LGUI, KC_LSFT, KC_PSCR, ONEQUAR, _______,
                                            _______, _______, _______,    _______, ADJUST,  _______
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  €   │  _   │  [   │  ]   │  ^   │                │  !   │  <   │  >   │  =   │  &   │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  \   │  /   │  {   │  }   │  *   │                │  ?   │  (   │  )   │  -   │  :   │  @   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  #   │  $   │  |   │  ~   │  ´   │                │  +   │  %   │  "   │  '   │  ;   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │  ⎇   │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_RAISE] = LAYOUT_split_3x6_3(
        _______, DE_EURO, DE_UNDS, DE_LBRC, DE_RBRC, DE_CIRC,                               DE_EXLM, DE_LABK, DE_RABK, DE_EQL,  DE_AMPR, _______,
        _______, DE_BSLS, DE_SLSH, DE_LCBR, DE_RCBR, DE_ASTR,                               DE_QUES, DE_LPRN, DE_RPRN, DE_MINS, DE_COLN, DE_AT,
        _______, DE_HASH, DE_DLR,  DE_PIPE, DE_TILD, DE_ACUT,                               DE_PLUS, DE_PERC, DE_DQUO, DE_QUOT, DE_SCLN, _______,
                                            _______, KC_LALT, _______,    _______, _______, _______
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ F12  │  F1  │  F2  │  F3  │  F4  │  F5  │                │  F6  │  F1  │  F2  │  F3  │  F4  │ F11  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  ⌘   │  ⎇   │  ⇧   │  ^   │CW_TOG│                │      │  F5  │  F6  │  F7  │  F8  │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │ KOY  │ QWE  │                │      │  F9  │ F10  │ F11  │ F12  │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_ADJUST] = LAYOUT_split_3x6_3(
        KC_F12,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                                 KC_F6,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F11,
        _______, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, CW_TOGG,                                XXXXXXX, KC_F5,   KC_F6,   KC_F7,   KC_F8,   XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, KOY,     QWERTY,                                XXXXXXX, KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______,
                                            _______, _______, _______,    _______, _______, _______
    ),

};


// ─── Chordal Hold ───────────────────────────────────────────────────────────
// Hand assignment for hold-tap arbitration:
//   'L' / 'R' — hold only fires if the next key is on the opposite hand.
//   '*'       — no chordal constraint (normal hold-tap behavior).
// Thumbs use '*' so layer-tap thumbs can still activate keys on the same hand
// (e.g. hold LOWERTAB on the left thumb to reach numbers on the left side).
const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM =
    LAYOUT_split_3x6_3(
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
                            '*', '*', '*',   '*', '*', '*'
    );


// ─── Caps Word ──────────────────────────────────────────────────────────────
// While Caps Word is active, these keys auto-shift; the rest end the word.
bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Letters: shift while Caps Word is on.
        case KC_A ... KC_Z:
        case DE_ADIA:
        case DE_ODIA:
        case DE_UDIA:
        case DE_SS:
            add_weak_mods(MOD_BIT(KC_LSFT));
            return true;
        // Continue without shift.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
        case DE_UNDS:
        case DE_MINS:
            return true;
        default:
            return false;  // any other key terminates Caps Word
    }
}


// ─── Default-layer toggles ──────────────────────────────────────────────────
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case KOY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_KOY);
            }
            return false;
        case QWERTY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWERTY);
            }
            return false;
    }
    return true;
}


// ─── OLED ───────────────────────────────────────────────────────────────────
// Master  (left):  layer name + mod indicators + caps-word indicator
// Slave   (right): Corne logo + Luna the dog + WPM
//
// Luna animation adapted from bsag/qmk_custom (originally HellSingCoder).
#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_270;  // portrait on both halves
}

// — Master: status panel ————————————————————————————————————————————————————
static void render_layer_name(void) {
    oled_write_P(PSTR("LAYER\n"), false);
    switch (get_highest_layer(layer_state | default_layer_state)) {
        case _QWERTY: oled_write_ln_P(PSTR("QWRTY"), false); break;
        case _KOY:    oled_write_ln_P(PSTR("KOY  "), false); break;
        case _LOWER:  oled_write_ln_P(PSTR("LWR  "), false); break;
        case _RAISE:  oled_write_ln_P(PSTR("RSE  "), false); break;
        case _ADJUST: oled_write_ln_P(PSTR("ADJ  "), false); break;
        default:      oled_write_ln_P(PSTR("?    "), false); break;
    }
}

static void render_mod_status(void) {
    uint8_t mods = get_mods() | get_oneshot_mods();
    oled_write_P(PSTR("MODS\n"), false);
    oled_write_P((mods & MOD_MASK_GUI)   ? PSTR("G") : PSTR("g"), false);
    oled_write_P((mods & MOD_MASK_ALT)   ? PSTR("A") : PSTR("a"), false);
    oled_write_P((mods & MOD_MASK_SHIFT) ? PSTR("S") : PSTR("s"), false);
    oled_write_P((mods & MOD_MASK_CTRL)  ? PSTR("C") : PSTR("c"), false);
    oled_write_P(PSTR(" \n"), false);
}

static void render_caps_word(void) {
    if (is_caps_word_on()) {
        oled_write_P(PSTR("CAPS\nWORD\n"), false);
    } else {
        oled_write_P(PSTR("\n\n"), false);
    }
}

static void render_master(void) {
    render_layer_name();
    oled_write_P(PSTR("\n"), false);
    render_mod_status();
    oled_write_P(PSTR("\n"), false);
    render_caps_word();
}

// — Slave: logo + Luna + WPM ———————————————————————————————————————————————
static void render_logo(void) {
    static const char PROGMEM crkbd_logo[] = {
        0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94,
        0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4,
        0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4,
        0
    };
    oled_write_P(crkbd_logo, false);
}

#define LUNA_FRAMES         2
#define LUNA_FRAME_DURATION 200   // ms per frame
#define LUNA_SIZE           96    // bytes per frame (32×24 px = 3 rows × 32 cols)

static uint8_t  luna_frame    = 0;
static uint16_t anim_timer    = 0;
static uint32_t last_keystroke = 0;

static void render_luna_sit(void) {
    static const char PROGMEM sit[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xe0,0xfc,
        0xfe,0xfd,0xfe,0xdc,0xfc,0xfc,0xfe,0x5d,0xfe,0xe0,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0xe0,0xf0,0xf8,0x1c,0xf0,0xf8,0xfc,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xfd,0xf9,0xfd,0x7f,0x03,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x07,0x0f,0x1f,0x1f,0x3f,0x3f,0x3f,0x37,
        0x21,0x13,0x3f,0x3f,0x3f,0x0f,0x11,0x1f,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xe0,0xfe,
        0xfd,0xfe,0xfc,0xdc,0xfc,0xfe,0xfd,0x5e,0xfc,0xe0,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0xe0,0xf0,0xf8,0xfc,0x80,0xf0,0xf8,0xfc,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xfd,0xf1,0xfd,0x7f,0x03,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x07,0x0f,0x1f,0x1f,0x3f,0x3f,0x3f,0x37,
        0x21,0x13,0x3f,0x3f,0x3f,0x0f,0x11,0x1f,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(sit[luna_frame], LUNA_SIZE);
}

static void render_luna_walk(void) {
    static const char PROGMEM walk[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xe0,0xf0,0xf0,0x70,0x30,0x20,0x00,0x80,0xc0,
        0xc0,0xf0,0xf8,0xf4,0xf8,0x70,0xf0,0xf0,0xf8,0x74,0xf8,0x80,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x07,0x0f,0xff,0xfd,0xfe,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf7,0xe7,0xf5,0x1f,0x0f,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x1f,0x3f,0x3f,0x3f,0x0f,0x11,0x1f,0x1f,
        0x03,0x07,0x1f,0x3f,0x3f,0x0f,0x13,0x1f,0x1f,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xe0,0xe0,0xe0,0xc0,0x80,0x00,0x00,0x00,
        0x00,0xe0,0xf0,0xe8,0xf0,0xe0,0xe0,0xe0,0xf0,0xe8,0xf0,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x1f,0x3f,0xfb,0xfd,0xfe,0xfe,0xfe,0xfe,0xfe,0xfe,0xfe,
        0xff,0xff,0xff,0xff,0xff,0xfe,0xff,0xef,0xcf,0xea,0x3f,0x1f,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x3f,0x3f,0x3f,0x0f,0x03,0x07,0x0f,0x1f,0x03,
        0x1f,0x1f,0x17,0x0f,0x1f,0x3f,0x3f,0x33,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(walk[luna_frame], LUNA_SIZE);
}

static void render_luna_run(void) {
    static const char PROGMEM run[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0xe0,0xf0,0xf8,0xf8,0xf8,0xb0,0xa0,0x80,0x80,0x80,0x80,0x80,
        0x80,0xc0,0xc0,0xfc,0xf4,0xe4,0xf8,0x70,0xf8,0xe4,0xf8,0x70,0xc0,0x80,0x00,0x00,
        0x00,0x00,0x00,0x00,0x01,0x63,0xe7,0xe7,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf7,0x67,0x37,0x35,0x1f,0x0f,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x0e,0x0f,0x07,0x07,0x07,0x07,0x03,0x03,0x03,0x01,0x01,
        0x03,0x03,0x07,0x0f,0x1f,0x3f,0x3b,0x33,0x07,0x07,0x06,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0xe0,0xf0,0xf0,0xf8,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,
        0x80,0x80,0xf8,0xe8,0xc8,0xf0,0xe0,0xf0,0xc8,0xf0,0xe0,0xc0,0x80,0x00,0x00,0x00,
        0x00,0x00,0x00,0x03,0x07,0x0f,0x1f,0x1f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xfe,0xef,0xcf,0x6f,0x6a,0x3f,0x1f,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x0f,0x1f,0x3f,0x3f,0x37,
        0x03,0x1f,0x3f,0x3f,0x1f,0x0f,0x1f,0x3f,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(run[luna_frame], LUNA_SIZE);
}

static void render_luna_bark(void) {
    static const char PROGMEM bark[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0xc0,0xe0,0xf0,0xf0,0x30,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x80,0xc0,
        0xfc,0xf4,0xe4,0xf8,0x70,0xf8,0xe4,0xf8,0x70,0xc0,0x80,0x00,0x00,0x00,0x00,0x00,
        0x00,0x03,0x07,0x0f,0x1f,0x1f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xf7,0xf7,0x37,0x35,0x1f,0x0f,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x0f,0x1f,0x3f,0x3f,0x37,0x03,0x03,
        0x07,0x0f,0x1f,0x3f,0x3b,0x33,0x07,0x07,0x06,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0xe0,0xf0,0xf0,0xf0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x80,0xc0,
        0xc0,0xec,0xf4,0xe4,0xf8,0x70,0xf8,0xe4,0xf8,0x70,0xc0,0x80,0x00,0x00,0x00,0x00,
        0x00,0x03,0x07,0x0f,0x1f,0x1f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x77,0x37,0x35,0x1f,0x0f,0x20,0x4a,0x09,0x10,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x0f,0x1f,0x3f,0x3f,0x37,0x03,0x03,
        0x07,0x0f,0x1f,0x3f,0x3b,0x33,0x07,0x07,0x06,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(bark[luna_frame], LUNA_SIZE);
}

static void render_luna_sneak(void) {
    static const char PROGMEM sneak[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xc0,0xc0,0xc0,0x80,0x00,0x00,0x00,0x00,
        0x00,0x00,0xc0,0x40,0x40,0x80,0x00,0x80,0x40,0x80,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x1e,0x3f,0xff,0xfb,0xfd,0xfd,0xfd,0xfd,0xfd,0xfc,0xfc,0xfc,
        0xfc,0xfe,0xff,0xff,0xfe,0xff,0xf7,0xff,0x7e,0x7f,0x57,0xfc,0xf8,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x1f,0x3f,0x3f,0x3f,0x0f,0x1f,0x1f,0x03,0x07,
        0x1f,0x3f,0x3f,0x3f,0x0f,0x1f,0x1f,0x07,0x07,0x03,0x03,0x01,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xc0,0xc0,0x80,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0xe0,0xa0,0x20,0xc0,0x80,0xc0,0x20,0xc0,0x80,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x3e,0x7f,0xf7,0xfb,0xfd,0xfd,0xfd,0xfd,0xfc,0xfc,0xfc,0xfc,
        0xfc,0xfe,0xff,0xff,0xff,0xff,0xfb,0xff,0xbf,0xbf,0xab,0xfe,0x7c,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x3f,0x3f,0x3f,0x0f,0x03,0x07,0x0f,0x1f,0x1f,0x07,
        0x1f,0x1f,0x0f,0x1f,0x3f,0x3f,0x37,0x07,0x03,0x01,0x01,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(sneak[luna_frame], LUNA_SIZE);
}

static void render_wpm(void) {
    char wpm_str[5];
    uint8_t n = get_current_wpm();
    wpm_str[0] = '0' + n / 100;
    wpm_str[1] = '0' + (n / 10) % 10;
    wpm_str[2] = '0' + n % 10;
    wpm_str[3] = '\n';
    wpm_str[4] = '\0';
    oled_write_P(PSTR("WPM\n"), false);
    oled_write(wpm_str, false);
}

static void render_slave(void) {
    // Top: small Corne logo (3 rows × 21 chars)
    render_logo();

    // Drive last_keystroke from sustained WPM (master sends it via split sync).
    static uint8_t prev_wpm = 0;
    if (get_current_wpm() > prev_wpm || get_mods()) {
        last_keystroke = timer_read32();
    }
    prev_wpm = get_current_wpm();

    // Pick which Luna frame to draw based on state.
    if (timer_elapsed(anim_timer) > LUNA_FRAME_DURATION) {
        anim_timer = timer_read();
        luna_frame ^= 1;
    }

    bool caps = host_keyboard_led_state().caps_lock || is_caps_word_on();
    uint32_t since = timer_elapsed32(last_keystroke);

    oled_set_cursor(0, 8);
    if      (get_mods() & MOD_MASK_SHIFT || caps)  render_luna_bark();
    else if (get_mods() & MOD_MASK_CAG)            render_luna_sneak();
    else if (since < LUNA_FRAME_DURATION * 2)      render_luna_run();
    else if (since < LUNA_FRAME_DURATION * 8)      render_luna_walk();
    else                                            render_luna_sit();

    oled_set_cursor(0, 14);
    render_wpm();
}

bool oled_task_user(void) {
    if (is_keyboard_master()) render_master();
    else                      render_slave();
    return false;
}
#endif // OLED_ENABLE
