// SPDX-License-Identifier: GPL-2.0-or-later
#include QMK_KEYBOARD_H
#include "keymap_german.h"


// ─── Layers ─────────────────────────────────────────────────────────────────
enum corne_layers {
    _QWERTY,
    _KOY,
    _LOWER,
    _RAISE,
    _ADJUST,
};

enum custom_keycodes {
    KOY = QK_USER,
    QWERTY,
};


// ─── Shortcuts ──────────────────────────────────────────────────────────────
// Layer access
#define LOWER       MO(_LOWER)
#define RAISE       MO(_RAISE)
#define ADJUST      MO(_ADJUST)

// Thumb cluster: layer-tap and mod-tap
#define LOWERTAB    LT(_LOWER,  KC_TAB)   // tap=Tab,   hold=Lower
#define RAISEBSPC   LT(_RAISE,  KC_BSPC)  // tap=BSpc,  hold=Raise
#define ALTTPEN     LT(_ADJUST, KC_ENT)   // tap=Enter, hold=Adjust
#define ALTTPES     LALT_T(KC_ESC)        // tap=Esc,   hold=Alt
#define SHIFTSPACE  LSFT_T(KC_SPC)        // tap=Space, hold=Shift

// Home-row mods on the KOY layer (GASC: GUI, Alt, Shift, Ctrl)
#define HMOD_GUI    LGUI_T(DE_H)
#define HMOD_ALT    LALT_T(DE_A)
#define HMOD_SHIFT  LSFT_T(DE_E)
#define HMOD_CTRL   LCTL_T(DE_I)

// Ctrl+letter shortcuts (German layout)
#define N_PASTE     LCTL(KC_V)
#define N_COPY      LCTL(KC_C)
#define N_CUT       LCTL(KC_X)
#define N_UNDO      LCTL(DE_Z)
#define N_REDO      LCTL(DE_Y)

// AltGr fractions
#define ONEHALF     ALGR(DE_4)
#define ONETHIR     ALGR(DE_5)
#define ONEQUAR     ALGR(DE_6)


// ─── Keymap ─────────────────────────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │  ⭾   │  Q   │  W   │  E   │  R   │  T   │                │  Y   │  U   │  I   │  O   │  P   │  ⌫   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⌘   │  A   │  S   │  D   │  F   │  G   │                │  H   │  J   │  K   │  L   │  ;   │  '   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⇧   │  Z   │  X   │  C   │  V   │  B   │                │  N   │  M   │  ,   │  .   │  /   │  ⇧   │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │  ^   │ ⭾Lwr │ ⏎Adj │  │  ␣   │ ⌫Rse │  ⎋⎇  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_QWERTY] = LAYOUT_split_3x6_3(
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                                  KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
        KC_LGUI, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                                  KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,                                  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
                                            KC_LCTL, LOWERTAB, ALTTPEN,    KC_SPC,    RAISEBSPC, ALTTPES
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │  Z   │  K   │  .   │  O   │  ,   │  Y   │                │  V   │  G   │  C   │  L   │  ß   │  ⌫   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⌘   │  H⌘  │  A⎇  │  E⇧  │  I^  │  U   │                │  D   │  T   │  R   │  N   │  S   │  F   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  ⇧   │  X   │  Q   │  ä   │  ü   │  ö   │                │  B   │  P   │  W   │  M   │  J   │  ⇧   │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │  ^   │ ⭾Lwr │ ⏎Adj │  │  ␣⇧  │ ⌫Rse │  ⎋⎇  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_KOY] = LAYOUT_split_3x6_3(
        DE_Z,    DE_K,      DE_DOT,    DE_O,       DE_COMM,   DE_Y,                              DE_V,    DE_G,    DE_C,    DE_L,    DE_SS,   KC_BSPC,
        KC_LGUI, HMOD_GUI,  HMOD_ALT,  HMOD_SHIFT, HMOD_CTRL, DE_U,                              DE_D,    DE_T,    DE_R,    DE_N,    DE_S,    DE_F,
        KC_LSFT, DE_X,      DE_Q,      DE_ADIA,    DE_UDIA,   DE_ODIA,                           DE_B,    DE_P,    DE_W,    DE_M,    DE_J,    KC_RSFT,
                                                   KC_LCTL,   LOWERTAB,  ALTTPEN,    SHIFTSPACE, RAISEBSPC, ALTTPES
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  1   │  2   │  3   │  4   │  5   │                │  6   │  7   │  8   │  9   │  0   │  ⌦   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ Vol+ │  ▶⏸  │  ⇤   │  ⇥   │  ^Z  │                │  Z   │  ◁   │  ▽   │  △   │  ▷   │  ⎋   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ Vol- │  ⏮   │  ⏭   │  ^C  │  ^V  │                │  ²   │  ⌘   │  ⇧   │  ⎙   │  ¼   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │ Adj  │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_LOWER] = LAYOUT_split_3x6_3(
        _______, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                                  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        _______, KC_VOLU, KC_MPLY, KC_HOME, KC_END,  N_UNDO,                                DE_Z,    KC_LEFT, KC_DOWN, KC_UP,   KC_RIGHT,KC_ESC,
        _______, KC_VOLD, KC_MPRV, KC_MNXT, N_COPY,  N_PASTE,                               DE_SUP2, KC_LGUI, KC_LSFT, KC_PSCR, ONEQUAR, _______,
                                            _______, _______, _______,    _______, ADJUST,  _______
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  €   │  _   │  [   │  ]   │  ^   │                │  !   │  <   │  >   │  =   │  &   │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  \   │  /   │  {   │  }   │  *   │                │  ?   │  (   │  )   │  -   │  :   │  @   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  #   │  $   │  |   │  ~   │  ´   │                │  +   │  %   │  "   │  '   │  ;   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │  ⎇   │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_RAISE] = LAYOUT_split_3x6_3(
        _______, DE_EURO, DE_UNDS, DE_LBRC, DE_RBRC, DE_CIRC,                               DE_EXLM, DE_LABK, DE_RABK, DE_EQL,  DE_AMPR, _______,
        _______, DE_BSLS, DE_SLSH, DE_LCBR, DE_RCBR, DE_ASTR,                               DE_QUES, DE_LPRN, DE_RPRN, DE_MINS, DE_COLN, DE_AT,
        _______, DE_HASH, DE_DLR,  DE_PIPE, DE_TILD, DE_ACUT,                               DE_PLUS, DE_PERC, DE_DQUO, DE_QUOT, DE_SCLN, _______,
                                            _______, KC_LALT, _______,    _______, _______, _______
    ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ F12  │  F1  │  F2  │  F3  │  F4  │  F5  │                │  F6  │  F1  │  F2  │  F3  │  F4  │ F11  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  ⌘   │  ⎇   │  ⇧   │  ^   │CW_TOG│                │      │  F5  │  F6  │  F7  │  F8  │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │ KOY  │ QWE  │                │      │  F9  │ F10  │ F11  │ F12  │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
    [_ADJUST] = LAYOUT_split_3x6_3(
        KC_F12,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                                 KC_F6,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F11,
        _______, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, CW_TOGG,                                XXXXXXX, KC_F5,   KC_F6,   KC_F7,   KC_F8,   XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, KOY,     QWERTY,                                XXXXXXX, KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______,
                                            _______, _______, _______,    _______, _______, _______
    ),

};


// ─── Chordal Hold ───────────────────────────────────────────────────────────
// Hand assignment for hold-tap arbitration:
//   'L' / 'R' — hold only fires if the next key is on the opposite hand.
//   '*'       — no chordal constraint (normal hold-tap behavior).
// Thumbs use '*' so layer-tap thumbs can still activate keys on the same hand
// (e.g. hold LOWERTAB on the left thumb to reach numbers on the left side).
const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM =
    LAYOUT_split_3x6_3(
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',                  'R', 'R', 'R', 'R', 'R', 'R',
                            '*', '*', '*',   '*', '*', '*'
    );


// ─── Caps Word ──────────────────────────────────────────────────────────────
// While Caps Word is active, these keys auto-shift; the rest end the word.
bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Letters: shift while Caps Word is on.
        case KC_A ... KC_Z:
        case DE_ADIA:
        case DE_ODIA:
        case DE_UDIA:
        case DE_SS:
            add_weak_mods(MOD_BIT(KC_LSFT));
            return true;
        // Continue without shift.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
        case DE_UNDS:
        case DE_MINS:
            return true;
        default:
            return false;  // any other key terminates Caps Word
    }
}


// ─── Default-layer toggles ──────────────────────────────────────────────────
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case KOY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_KOY);
            }
            return false;
        case QWERTY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWERTY);
            }
            return false;
    }
    return true;
}


// ─── OLED ───────────────────────────────────────────────────────────────────
// Master  (left):  layer name + mod indicators + caps-word indicator
// Slave   (right): Corne logo + Luna the dog + WPM
//
// Luna animation adapted from bsag/qmk_custom (originally HellSingCoder).
#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_270;  // both halves portrait (32 wide × 128 tall)
}

// — Helpers ————————————————————————————————————————————————————————————————
static const char *layer_name(void) {
    switch (get_highest_layer(layer_state | default_layer_state)) {
        case _QWERTY: return "QWERTY";
        case _KOY:    return "KOY   ";
        case _LOWER:  return "LOWER ";
        case _RAISE:  return "RAISE ";
        case _ADJUST: return "ADJUST";
        default:      return "?     ";
    }
}

static void write_mods(uint8_t mods) {
    oled_write_P((mods & MOD_MASK_GUI)   ? PSTR("G") : PSTR("g"), false);
    oled_write_P((mods & MOD_MASK_ALT)   ? PSTR("A") : PSTR("a"), false);
    oled_write_P((mods & MOD_MASK_SHIFT) ? PSTR("S") : PSTR("s"), false);
    oled_write_P((mods & MOD_MASK_CTRL)  ? PSTR("C") : PSTR("c"), false);
}

// — Slave: status panel (32×128 portrait, 5 chars × 16 rows) ——————————————
__attribute__((unused)) static void render_status_panel(void) {
    oled_set_cursor(0, 0);
    oled_write_P(PSTR("LAYER\n"), false);
    oled_write(layer_name(), false);  // 5/6 chars; "ADJUST" wraps but readable
    oled_write_P(PSTR("\n\n"), false);

    oled_write_P(PSTR("MODS\n"), false);
    write_mods(get_mods() | get_oneshot_mods());
    oled_write_P(PSTR(" \n\n"), false);

    oled_write_P(is_caps_word_on() ? PSTR("CAPS\nWORD\n") : PSTR("    \n    \n"), false);
    oled_write_P(host_keyboard_led_state().caps_lock ? PSTR("\nLOCK") : PSTR("\n    "), false);
}

// — Luna animation ————————————————————————————————————————————————————————
#define LUNA_FRAMES         2
#define LUNA_FRAME_DURATION 200   // ms per frame
#define LUNA_SIZE           96    // bytes per frame (32×24 px = 3 rows × 32 cols)

static uint8_t  luna_frame    = 0;
static uint16_t anim_timer    = 0;
static uint32_t last_keystroke = 0;

static void render_luna_sit(void) {
    static const char PROGMEM sit[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xe0,0xfc,
        0xfe,0xfd,0xfe,0xdc,0xfc,0xfc,0xfe,0x5d,0xfe,0xe0,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0xe0,0xf0,0xf8,0x1c,0xf0,0xf8,0xfc,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xfd,0xf9,0xfd,0x7f,0x03,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x07,0x0f,0x1f,0x1f,0x3f,0x3f,0x3f,0x37,
        0x21,0x13,0x3f,0x3f,0x3f,0x0f,0x11,0x1f,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xe0,0xfe,
        0xfd,0xfe,0xfc,0xdc,0xfc,0xfe,0xfd,0x5e,0xfc,0xe0,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0xe0,0xf0,0xf8,0xfc,0x80,0xf0,0xf8,0xfc,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xfd,0xf1,0xfd,0x7f,0x03,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x07,0x0f,0x1f,0x1f,0x3f,0x3f,0x3f,0x37,
        0x21,0x13,0x3f,0x3f,0x3f,0x0f,0x11,0x1f,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(sit[luna_frame], LUNA_SIZE);
}

static void render_luna_walk(void) {
    static const char PROGMEM walk[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xe0,0xf0,0xf0,0x70,0x30,0x20,0x00,0x80,0xc0,
        0xc0,0xf0,0xf8,0xf4,0xf8,0x70,0xf0,0xf0,0xf8,0x74,0xf8,0x80,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x07,0x0f,0xff,0xfd,0xfe,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf7,0xe7,0xf5,0x1f,0x0f,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x1f,0x3f,0x3f,0x3f,0x0f,0x11,0x1f,0x1f,
        0x03,0x07,0x1f,0x3f,0x3f,0x0f,0x13,0x1f,0x1f,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xe0,0xe0,0xe0,0xc0,0x80,0x00,0x00,0x00,
        0x00,0xe0,0xf0,0xe8,0xf0,0xe0,0xe0,0xe0,0xf0,0xe8,0xf0,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x1f,0x3f,0xfb,0xfd,0xfe,0xfe,0xfe,0xfe,0xfe,0xfe,0xfe,
        0xff,0xff,0xff,0xff,0xff,0xfe,0xff,0xef,0xcf,0xea,0x3f,0x1f,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x3f,0x3f,0x3f,0x0f,0x03,0x07,0x0f,0x1f,0x03,
        0x1f,0x1f,0x17,0x0f,0x1f,0x3f,0x3f,0x33,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(walk[luna_frame], LUNA_SIZE);
}

static void render_luna_run(void) {
    static const char PROGMEM run[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0xe0,0xf0,0xf8,0xf8,0xf8,0xb0,0xa0,0x80,0x80,0x80,0x80,0x80,
        0x80,0xc0,0xc0,0xfc,0xf4,0xe4,0xf8,0x70,0xf8,0xe4,0xf8,0x70,0xc0,0x80,0x00,0x00,
        0x00,0x00,0x00,0x00,0x01,0x63,0xe7,0xe7,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf7,0x67,0x37,0x35,0x1f,0x0f,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x0e,0x0f,0x07,0x07,0x07,0x07,0x03,0x03,0x03,0x01,0x01,
        0x03,0x03,0x07,0x0f,0x1f,0x3f,0x3b,0x33,0x07,0x07,0x06,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0xe0,0xf0,0xf0,0xf8,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,
        0x80,0x80,0xf8,0xe8,0xc8,0xf0,0xe0,0xf0,0xc8,0xf0,0xe0,0xc0,0x80,0x00,0x00,0x00,
        0x00,0x00,0x00,0x03,0x07,0x0f,0x1f,0x1f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xfe,0xef,0xcf,0x6f,0x6a,0x3f,0x1f,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x0f,0x1f,0x3f,0x3f,0x37,
        0x03,0x1f,0x3f,0x3f,0x1f,0x0f,0x1f,0x3f,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(run[luna_frame], LUNA_SIZE);
}

static void render_luna_bark(void) {
    static const char PROGMEM bark[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0xc0,0xe0,0xf0,0xf0,0x30,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x80,0xc0,
        0xfc,0xf4,0xe4,0xf8,0x70,0xf8,0xe4,0xf8,0x70,0xc0,0x80,0x00,0x00,0x00,0x00,0x00,
        0x00,0x03,0x07,0x0f,0x1f,0x1f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xf7,0xf7,0x37,0x35,0x1f,0x0f,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x0f,0x1f,0x3f,0x3f,0x37,0x03,0x03,
        0x07,0x0f,0x1f,0x3f,0x3b,0x33,0x07,0x07,0x06,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    },{
        0x00,0xe0,0xf0,0xf0,0xf0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x80,0xc0,
        0xc0,0xec,0xf4,0xe4,0xf8,0x70,0xf8,0xe4,0xf8,0x70,0xc0,0x80,0x00,0x00,0x00,0x00,
        0x00,0x03,0x07,0x0f,0x1f,0x1f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x77,0x37,0x35,0x1f,0x0f,0x20,0x4a,0x09,0x10,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x03,0x0f,0x1f,0x3f,0x3f,0x37,0x03,0x03,
        0x07,0x0f,0x1f,0x3f,0x3b,0x33,0x07,0x07,0x06,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(bark[luna_frame], LUNA_SIZE);
}

static void render_luna_sneak(void) {
    static const char PROGMEM sneak[LUNA_FRAMES][LUNA_SIZE] = {{
        0x00,0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xc0,0xc0,0xc0,0x80,0x00,0x00,0x00,0x00,
        0x00,0x00,0xc0,0x40,0x40,0x80,0x00,0x80,0x40,0x80,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x1e,0x3f,0xff,0xfb,0xfd,0xfd,0xfd,0xfd,0xfd,0xfc,0xfc,0xfc,
        0xfc,0xfe,0xff,0xff,0xfe,0xff,0xf7,0xff,0x7e,0x7f,0x57,0xfc,0xf8,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x1f,0x3f,0x3f,0x3f,0x0f,0x1f,0x1f,0x03,0x07,
        0x1f,0x3f,0x3f,0x3f,0x0f,0x1f,0x1f,0x07,0x07,0x03,0x03,0x01,0x00,0x00,0x00,0x00
    },{
        0x00,0x00,0x00,0x00,0x00,0x00,0x80,0xc0,0xc0,0xc0,0x80,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0xe0,0xa0,0x20,0xc0,0x80,0xc0,0x20,0xc0,0x80,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x3e,0x7f,0xf7,0xfb,0xfd,0xfd,0xfd,0xfd,0xfc,0xfc,0xfc,0xfc,
        0xfc,0xfe,0xff,0xff,0xff,0xff,0xfb,0xff,0xbf,0xbf,0xab,0xfe,0x7c,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x3f,0x3f,0x3f,0x0f,0x03,0x07,0x0f,0x1f,0x1f,0x07,
        0x1f,0x1f,0x0f,0x1f,0x3f,0x3f,0x37,0x07,0x03,0x01,0x01,0x00,0x00,0x00,0x00,0x00
    }};
    oled_write_raw_P(sneak[luna_frame], LUNA_SIZE);
}

// — Typing intensity bar — full-width 32 px horizontal at given row ————————
static void render_wpm_bar(uint8_t row) {
    uint8_t n    = get_current_wpm();
    uint8_t fill = (n >= 100) ? 32 : (n * 32 / 100);
    char bar[32];
    for (uint8_t i = 0; i < 32; i++) bar[i] = (i < fill) ? 0xfe : 0x80;
    oled_set_cursor(0, row);
    oled_write_raw(bar, 32);
}

// — Luna panel: Luna + bar + big WPM (32×128 portrait) —————————————————————
__attribute__((unused)) static void render_luna_panel(void) {
    // Drive last_keystroke from sustained WPM.
    static uint8_t prev_wpm = 0;
    if (get_current_wpm() > prev_wpm || get_mods()) {
        last_keystroke = timer_read32();
    }
    prev_wpm = get_current_wpm();

    // Tick frame.
    if (timer_elapsed(anim_timer) > LUNA_FRAME_DURATION) {
        anim_timer = timer_read();
        luna_frame ^= 1;
    }

    bool caps = host_keyboard_led_state().caps_lock || is_caps_word_on();
    uint32_t since = timer_elapsed32(last_keystroke);

    // Top: layer name (rows 0..1)
    oled_set_cursor(0, 0);
    oled_write_P(PSTR("LAYR\n"), false);
    oled_write(layer_name(), false);

    // Luna in the middle (rows 4..6 = 24 px tall, 32 wide).
    oled_set_cursor(0, 4);
    if      (get_mods() & MOD_MASK_SHIFT || caps)  render_luna_bark();
    else if (get_mods() & MOD_MASK_CAG)            render_luna_sneak();
    else if (since < LUNA_FRAME_DURATION * 2)      render_luna_run();
    else if (since < LUNA_FRAME_DURATION * 8)      render_luna_walk();
    else                                            render_luna_sit();

    // "WPM" label centered (5 chars across the full 5-char-wide row).
    oled_set_cursor(0, 9);
    oled_write_P(PSTR(" WPM "), false);

    // WPM number centered: " NNN ".
    uint8_t n = get_current_wpm();
    char w[6];
    w[0] = ' ';
    w[1] = '0' + n / 100;
    w[2] = '0' + (n / 10) % 10;
    w[3] = '0' + n % 10;
    w[4] = ' ';
    w[5] = '\0';
    oled_set_cursor(0, 10);
    oled_write(w, false);

    // Intensity bar at row 13.
    render_wpm_bar(13);
}

// — OLED size diagnostic — define OLED_DIAG in config.h to activate ————————
// Flash with this on, look at both screens; the values printed are the
// compile-time OLED_DISPLAY_WIDTH / HEIGHT QMK is driving. If those don't
// match what you physically see, change the OLED_DISPLAY_* define accordingly.
#ifdef OLED_DIAG
#  define DIAG_S2(x) #x
#  define DIAG_S(x)  DIAG_S2(x)
static void render_oled_diag(void) {
    oled_set_cursor(0, 0);
    oled_write_P(PSTR("W:" DIAG_S(OLED_DISPLAY_WIDTH) "\n"), false);
    oled_write_P(PSTR("H:" DIAG_S(OLED_DISPLAY_HEIGHT) "\n"), false);
    oled_write_P(PSTR("rows" "\n"), false);
    char r[3] = { '0' + OLED_DISPLAY_HEIGHT / 8 / 10, '0' + (OLED_DISPLAY_HEIGHT / 8) % 10, '\0' };
    oled_write(r, false);
    oled_write_P(PSTR("\ncols\n"), false);
    char c[4] = { '0' + OLED_DISPLAY_WIDTH / 100, '0' + (OLED_DISPLAY_WIDTH / 10) % 10, '0' + OLED_DISPLAY_WIDTH % 10, '\0' };
    oled_write(c, false);
    // Border: top row + bottom row of full-width 0xff bytes
    char border[OLED_DISPLAY_WIDTH];
    for (uint16_t i = 0; i < OLED_DISPLAY_WIDTH; i++) border[i] = 0xff;
    oled_set_cursor(0, 0);
    oled_write_raw(border, OLED_DISPLAY_WIDTH);
    oled_set_cursor(0, OLED_DISPLAY_HEIGHT / 8 - 1);
    oled_write_raw(border, OLED_DISPLAY_WIDTH);
}
#endif

// — Fill-all diagnostic — define OLED_FILL_TEST in config.h to activate ————
// Lights every pixel QMK believes the display has. If you see black bands
// after this, those bands are the OLED's physical bezel (no pixels there)
// and cannot be fixed in firmware. If they light up, the QMK display
// dimensions or OLED IC config are wrong.
#ifdef OLED_FILL_TEST
static void render_fill_all(void) {
    char row[OLED_DISPLAY_WIDTH];
    for (uint16_t i = 0; i < OLED_DISPLAY_WIDTH; i++) row[i] = 0xff;
    for (uint8_t r = 0; r < OLED_DISPLAY_HEIGHT / 8; r++) {
        oled_set_cursor(0, r);
        oled_write_raw(row, OLED_DISPLAY_WIDTH);
    }
}
#endif

bool oled_task_user(void) {
#if defined(OLED_FILL_TEST)
    render_fill_all();
#elif defined(OLED_DIAG)
    render_oled_diag();
#else
    // Master shows Luna + WPM; slave shows the status panel.
    if (is_keyboard_master()) render_luna_panel();
    else                      render_status_panel();
#endif
    return false;
}
#endif // OLED_ENABLE
